### PR TITLE
Fixed class name typo

### PR DESCRIPTION
**Pull request by dominiksagi**

### CODE REVIEW

**Comment by jeandormehl** [comment]
Any movement on this?

**Comment by DannyvdSluijs** [comment]
Ran into the same issue, and applied the same fix as the PR is doing.

**Comment by DannyvdSluijs** [comment]
@weierophinney any change this PR can be merged and a patch release 1.3.1 can be brought to life ?

**Comment by weierophinney** [comment]
@dominiksagi just for future reference: submit bugfixes against master, and feature changes against develop. I'll cherry pick this into master for now.

**Pull request closed without merging**
